### ISSUE TITLE
请问出现如下错误是为何？语法错误？

### ISSUE THREAD

**Issue by boyywzq** [DipperStar/SNH48Ticket#6]
![qq 20180102204249](https://user-images.githubusercontent.com/35026931/34484119-a81f429c-effd-11e7-945a-1df81bce01eb.png)

**Comment by DipperStar** [comment]
这是bug，把eval那一行改成for i in json.loads(requests.get(url).content):

**Comment by boyywzq** [comment]
辛苦啦，刚点进来发现还专门做了使用方法哈哈哈，早点休息吧
